#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
$HOME/.config/polybar/launch.sh
$HOME/.local/bin/remaps & spotify-listener & disown & nitrogen --restore & dunst

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a spotify desktop='^3'
