alias git='TZ=America/New_York /usr/bin/git'
alias v="vim"
alias nv="nvim"
alias svim='sudo vim'
alias sv='sudo vim'
alias em="emacs -nw"
alias sync="git sync"
alias merge="git merge"
alias publish="git publish"
alias cleanup='git branch --merged | egrep -v "(^\*|master|develop)" | xargs git branch -d'
alias gc="git co"
alias create="git co -b"
alias qq="exit"
alias att="tmux attach"
alias det="tmux detach"
alias t="tmux"
alias pg-start="systemctl start postgresql.service"
alias pg-stop="systemctl stop postgresql.service"
alias pg-status="systemctl status postgresql.service"
alias pull="git pull --ff-only"
alias pullsub="git submodule update --init --recursive"
alias rebase="git rebase"
alias cfw="vim ~/.config/i3/config"
alias cfb="sudo vim /sys/class/backlight/amdgpu_bl0/brightness"
alias cfs="vim ~/.config/fish/config.fish"
alias cfa="vim ~/.config/fish/alias.fish"
alias cfe="vim ~/.config/fish/env.fish"
alias cft="vim ~/.tmux.conf"
alias cf=" vim ~/.config"
alias ls="exa --long --header --git"
alias lsr="ranger"
alias g='ghq'
alias gg='ghq get -u .'

